<?php
/**
 * Created by PhpStorm.
 * User: leila
 * Date: 04/12/2018
 * Time: 11:50
 */

require_once 'SecureBaseController.php';
require_once  __DIR__.'/../models/ClientModel.php';
require_once  __DIR__.'/../models/ItemFileModel.php';

class ClientsController extends SecureBaseController
{
    private $items;
    function __construct(){
        parent::__construct();
        $this->model = new ClientModel();
        $this->items = new ItemFileModel();
    }

    function getSimpleClient(){
        $this->returnSuccess(200,$this->model->findAllClientName());
    }

    function getClients(){

        if($_GET['order'] == "name"){
            $list_clients=$this->getModel()->findAllByName($this->getFilters(),$this->getPaginator());
        }else{
            $list_clients=$this->getModel()->findAllByDebt($this->getFilters(),$this->getPaginator());
        }


        for ($i = 0; $i < count($list_clients); ++$i) {

            $amount=$this->items->sum($list_clients[$i]['id']);

            $this->model->update($list_clients[$i]['id'],array('debt'=> $amount['total']));

        }
        $this->returnSuccess(200, $list_clients);
    }

    function get(){

       $this->beforeMethod();
        error_log("ale");
        //error_log("SERVER: ".print_r($_SERVER,true));
        if(isset($_GET['method'])){
            $this->method();
        }else if($this->validateId()){
            $entity = $this->getModel()->findById($_GET['id']);
            if(!empty($entity)){
                $this->returnSuccess(200,$entity);
            }else{
                $this->returnError(404,"ENTITY NOT FOUND");
            }

        }else{
            $this->getClients();
           // $this->returnSuccess(200,$this->getModel()->findAllByName($this->getFilters(),$this->getPaginator()));
        }
    }

    public function getFilters()
    {

        $filters = parent::getFilters(); // TODO: Change the autogenerated stub
        if(isset($_GET['query']) && !empty($_GET['query'])){
            $filters[] = 'name like "%'.$_GET['query'].'%"';
        }
        return $filters;
    }

}