<?php
/**
 * Created by PhpStorm.
 * User: leila
 * Date: 19/12/2018
 * Time: 17:36
 */

require_once 'BaseController.php';
require_once  __DIR__.'/../models/ExtractionModel.php';
require_once  __DIR__.'/../models/BoxModel.php';

class ExtractionsController extends BaseController
{

    private $boxes;
    function __construct(){
        parent::__construct();
        $this->model = new ExtractionModel();
        $this->boxes= new BoxModel();
    }

    function updateBox($data){

        $created=$data['created'];

        $parts = explode(" ", $created);
        $date=$parts[0]." 00:00:00";
        $next_date = date('Y-m-d', strtotime( $parts[0].' +1 day'));
        $dateTo=$next_date." 00:00:00";
        $filters= array();
        $filters[] = 'created >= "'.$date.'"';
        $filters[] = 'created < "'.$dateTo.'"';

        $box=$this->boxes->find($filters);

        $totalAmount=$this->getModel()->amountByExtractionsDay($date,$dateTo);

        $this->boxes->update($box['id'],array('deposit'=> $totalAmount));

    }

    function put(){
        $data = (array) json_decode(file_get_contents("php://input"));
        parent::put();
        $this->updateBox($data);

    }
    function post()
    {
        $data = (array) json_decode(file_get_contents("php://input"));
        parent::post(); // TODO: Change the autogenerated stub
        $this->updateBox($data);
    }

    function delete()
    {
        $extraction_id = $_GET['id'];
        $extraction = $this->getModel()->findById($extraction_id);
        parent::delete(); // TODO: Change the autogenerated stub
        $this->updateBox($extraction);

    }


    function amountExtractions(){

        if(isset($_GET['date']) && isset($_GET['dateTo'])){

            $totalAmount=$this->getModel()->amountByExtractionsDay($_GET['date'],$_GET['dateTo']);
            $this->returnSuccess(200,$totalAmount);
        }
    }

}