<?php
/**
 * Created by PhpStorm.
 * User: leila
 * Date: 19/12/2018
 * Time: 17:36
 */

require_once 'SecureBaseController.php';
require_once  __DIR__.'/../models/ExtractionModel.php';
require_once  __DIR__.'/../models/BoxModel.php';

class ExtractionsController extends SecureBaseController
{

    private $boxes;
    function __construct(){
        parent::__construct();
        $this->model = new ExtractionModel();
        $this->boxes= new BoxModel();
    }

    function getDatesMonth($data){

        $partsYearMonthDay=explode("-", $data);
        $partsYearMonthDay[2]=01;

        $date= $partsYearMonthDay[0]."-".$partsYearMonthDay[1]."-".$partsYearMonthDay[2]." 00:00:00";

        $next_month = date('Y-m-d', strtotime( $date.' +1 month'));
        $dateTo=$next_month." 00:00:00";
        $result=array('date' => $date, 'dateTo' => $dateTo);

        return $result;
    }


    function getDates($data){

        $parts = explode(" ", $data);
        $date=$parts[0]." 00:00:00";
        $next_date = date('Y-m-d', strtotime( $parts[0].' +1 day'));
        $dateTo=$next_date." 00:00:00";
        $result=array('date' => $date, 'dateTo' => $dateTo);
        return $result;
    }


    function filtersType($dates){

        $filters=array();

        if(isset($_GET['type'])) {
            if ($_GET['type'] != "Todo") {
                $filters[] = 'type = "' . $_GET['type'] . '"';
            }
        }

        $filters[] = 'created >= "'.$dates['date'].'"';
        $filters[] = 'created < "'.$dates['dateTo'].'"';

        return $filters;
    }


    function getExtractions(){

        if($_GET['groupby'] === "month"){
            $listDays=$this->model->getMonthsGroup($this->getPaginator());
        }else{
            $listDays=$this->model->getDaysGroup($this->getPaginator());
        }

        $report=array();
        for ($k = 0; $k < count($listDays); ++$k) {

            if($_GET['groupby'] === "month"){

                $dates=$this->getDatesMonth($listDays[$k]['created']);
            }else{
                $dates=$this->getDates($listDays[$k]['created']);
            }
           //  $dates=$this->getDates($listDays[$k]['created']);

             $amountByDay=$this->model->amountByExtractionsDay2($this->filtersType($dates));

             $listExtrByDay= $this->model->listAll($this->filtersType($dates));

            $report[]=array('created'=>$listDays[$k]['created'],'amountDay' => $amountByDay['total'],'listExtractions' => $listExtrByDay);
        }
        $this->returnSuccess(200,$report);
    }



    function put(){
        $data = (array) json_decode(file_get_contents("php://input"));
        parent::put();
        $this->updateBox($data);
    }

    function post()
    {
        $data = (array) json_decode(file_get_contents("php://input"));
        parent::post(); // TODO: Change the autogenerated stub
        $this->updateBox($data);
    }

    function delete()
    {
        $extraction_id = $_GET['id'];
        $extraction = $this->getModel()->findById($extraction_id);
        parent::delete(); // TODO: Change the autogenerated stub
        $this->updateBox($extraction);

    }

    function amountExtractions(){

        if(isset($_GET['date']) && isset($_GET['dateTo'])){
            $totalAmount=$this->getModel()->amountByExtractionsDay($_GET['date'],$_GET['dateTo']);
            $this->returnSuccess(200,$totalAmount);
        }
    }


    function updateBox($data){

        $created=$data['created'];

        $parts = explode(" ", $created);
        $date=$parts[0]." 00:00:00";
        $next_date = date('Y-m-d', strtotime( $parts[0].' +1 day'));
        $dateTo=$next_date." 00:00:00";
        $filters= array();
        $filters[] = 'created >= "'.$date.'"';
        $filters[] = 'created < "'.$dateTo.'"';

        $box=$this->boxes->find($filters);

        $totalAmount=$this->getModel()->amountByExtractionsDay($date,$dateTo);

        $this->boxes->update($box['id'],array('deposit'=> $totalAmount));

    }

}