<?php
/**
 * Created by PhpStorm.
 * User: leila
 * Date: 05/04/2019
 * Time: 14:41
 */

require_once 'BaseController.php';
require_once  __DIR__.'/../models/StockEventModel.php';
require_once  __DIR__.'/../models/ProductModel.php';

class StockEventsController extends BaseController
{
    private $products;
    function __construct(){
        parent::__construct();
        $this->model = new StockEventModel();
        $this->products = new ProductModel();
    }

    function getBalance(){

        $this->returnSuccess(200,$this->getModel()->findAll($this->getFilters(),$this->getPaginator()));


    }
    function post()
    {
        parent::post(); // TODO: Change the autogenerated stub
        $data = (array) json_decode(file_get_contents("php://input"));

        $this->updateStockProduct($data['id_product'],$data['stock_in'],$data['stock_out']);
    }


    function updateStockProduct($id,$valueIn,$valueOut){

       $prod= $this->products->findById($id);
        if($prod){
            $val=$valueIn + $prod['stock'] - $valueOut;
            $this->products->update($id,array('stock'=> $val ));
        }
    }
}