<?php
/**
 * Created by PhpStorm.
 * User: leila
 * Date: 04/12/2018
 * Time: 12:38
 */

require_once 'BaseModel.php';
require_once 'ClientModel.php';

class ItemFileModel extends BaseModel
{
    public function __construct()
    {
        parent::__construct();
        $this->tableName = 'items_file';
    }

    public function save($data)
    {
      //  $data['previous_balance']=$this->sum($data['client_id']);
        return parent::save($data); // TODO: Change the autogenerated stub
    }

}